title: "Digital Tool Kit"
author: "DataTrainUBRA"
only_build_toc_files: true

html:
  use_repository_button: true
  use_download_button: true
  theme:
    sidebar_expandable: true
    navigation_with_keys: true

repository:
  url: https://github.com/DataTrainUBRA/DigitalToolkit_myst_book
  path_to_book: "book"
